# Generated by Django 5.2.4 on 2025-07-21 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("data_pipeline", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Name of the task type (e.g., 'retrieval', 'processing')", max_length=255, unique=True)),
                ("name_en", models.CharField(help_text="Name of the task type (e.g., 'retrieval', 'processing')", max_length=255, null=True, unique=True)),
                ("name_ar", models.CharField(help_text="Name of the task type (e.g., 'retrieval', 'processing')", max_length=255, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TaskExecution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_id", models.CharField(help_text="Unique Celery task ID", max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("started", "Started"), ("success", "Success"), ("failure", "Failure"), ("retry", "Retry"), ("revoked", "Revoked")],
                        default="pending",
                        help_text="Current status of the task execution",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, help_text="When the task started execution", null=True)),
                ("completed_at", models.DateTimeField(blank=True, help_text="When the task completed (success or failure)", null=True)),
                ("result", models.JSONField(blank=True, help_text="Task result data (success case)", null=True)),
                ("error_message", models.TextField(blank=True, help_text="Error message if task failed")),
                ("retry_count", models.IntegerField(default=0, help_text="Number of times this task has been retried")),
                ("max_retries", models.IntegerField(default=3, help_text="Maximum number of retries allowed")),
                ("arg1", models.BigIntegerField(blank=True, help_text="First argument/parameter for the task (e.g., source ID)", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(blank=True, help_text="Related data pipeline source", null=True, on_delete=django.db.models.deletion.CASCADE, to="data_pipeline.source"),
                ),
                (
                    "variable",
                    models.ForeignKey(blank=True, help_text="Related data pipeline variable", null=True, on_delete=django.db.models.deletion.CASCADE, to="data_pipeline.variable"),
                ),
                (
                    "task_type",
                    models.ForeignKey(
                        help_text="Type of task being executed", on_delete=django.db.models.deletion.PROTECT, related_name="executions", to="task_monitoring.tasktype"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["task_id"], name="task_monito_task_id_e555a5_idx"),
                    models.Index(fields=["task_type", "status"], name="task_monito_task_ty_56d1d5_idx"),
                    models.Index(fields=["status", "created_at"], name="task_monito_status_b85dfe_idx"),
                    models.Index(fields=["source", "task_type"], name="task_monito_source__f32c5b_idx"),
                    models.Index(fields=["variable", "task_type"], name="task_monito_variabl_10134b_idx"),
                ],
            },
        ),
    ]
