# Generated by Django 5.2.4 on 2025-09-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_monitoring', '0002_alter_tasktype_created_at_alter_tasktype_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, help_text='Celery task ID this log entry belongs to', max_length=255)),
                ('level', models.IntegerField(choices=[(10, 'DEBUG'), (20, 'INFO'), (30, 'WARNING'), (40, 'ERROR'), (50, 'CRITICAL')], default=20, help_text='Log level (10=DEBUG, 20=INFO, 30=WARNING, 40=ERROR, 50=CRITICAL)')),
                ('level_name', models.CharField(default='INFO', help_text='Human-readable log level name', max_length=10)),
                ('message', models.TextField(help_text='Log message content')),
                ('module', models.CharField(blank=True, help_text='Python module that generated the log', max_length=255)),
                ('function_name', models.CharField(blank=True, help_text='Function name that generated the log', max_length=255)),
                ('line_number', models.IntegerField(blank=True, help_text='Line number where log was generated', null=True)),
                ('thread', models.CharField(blank=True, help_text='Thread ID/name', max_length=100)),
                ('process', models.CharField(blank=True, help_text='Process ID/name', max_length=100)),
                ('extra_data', models.JSONField(blank=True, help_text='Additional structured data from the log record', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this log entry was created')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['task_id', 'timestamp'], name='task_monito_task_id_9ac7b5_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['task_id', 'level'], name='task_monito_task_id_f09e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['level', 'timestamp'], name='task_monito_level_1bc33b_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklog',
            index=models.Index(fields=['timestamp'], name='task_monito_timesta_7e9a24_idx'),
        ),
    ]
