# Generated by Django 5.2.4 on 2025-09-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_monitoring', '0003_add_task_log_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tasklog',
            new_name='task_monito_task_id_f39410_idx',
            old_name='task_monito_task_id_9ac7b5_idx',
        ),
        migrations.RenameIndex(
            model_name='tasklog',
            new_name='task_monito_task_id_04e42f_idx',
            old_name='task_monito_task_id_f09e3f_idx',
        ),
        migrations.RenameIndex(
            model_name='tasklog',
            new_name='task_monito_level_42e0e0_idx',
            old_name='task_monito_level_1bc33b_idx',
        ),
        migrations.RenameIndex(
            model_name='tasklog',
            new_name='task_monito_timesta_22c8b7_idx',
            old_name='task_monito_timesta_7e9a24_idx',
        ),
    ]
