# Generated by Django 5.2.4 on 2025-09-11 15:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("alerts", "0002_shocktype_color_shocktype_css_class_shocktype_icon"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("location", "0010_unmatchedlocation_potential_matches_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Detector",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Human-readable detector identifier", max_length=255, unique=True)),
                ("description", models.TextField(blank=True, help_text="Detailed description of what this detector analyzes")),
                ("class_name", models.CharField(help_text="Python class reference for dynamic loading (e.g., 'ConflictSurgeDetector')", max_length=255)),
                ("active", models.BooleanField(default=True, help_text="Enable/disable detector execution")),
                ("configuration", models.JSONField(blank=True, default=dict, help_text="Detector-specific configuration parameters")),
                ("last_run", models.DateTimeField(blank=True, help_text="Timestamp of most recent execution", null=True)),
                ("run_count", models.PositiveIntegerField(default=0, help_text="Total number of executions")),
                ("detection_count", models.PositiveIntegerField(default=0, help_text="Total detections created (performance metric)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        help_text="Scheduled execution task (optional for manual-only detectors)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_celery_beat.periodictask",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Detection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("detection_timestamp", models.DateTimeField(help_text="When the detected event/condition occurred")),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="Detection confidence score (0-1)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)],
                    ),
                ),
                ("detection_data", models.JSONField(default=dict, help_text="Detector-specific data and context")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("processed", "Processed"), ("dismissed", "Dismissed")], default="pending", help_text="Processing status", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When detection was created")),
                ("processed_at", models.DateTimeField(blank=True, help_text="When detection was processed/dismissed", null=True)),
                (
                    "alert",
                    models.ForeignKey(blank=True, help_text="Generated alert (null if not processed)", null=True, on_delete=django.db.models.deletion.SET_NULL, to="alerts.alert"),
                ),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to original detection if this is a duplicate",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="alert_framework.detection",
                    ),
                ),
                ("locations", models.ManyToManyField(blank=True, help_text="Affected locations", to="location.location")),
                ("shock_type", models.ForeignKey(blank=True, help_text="Shock type categorization", null=True, on_delete=django.db.models.deletion.PROTECT, to="alerts.shocktype")),
                (
                    "detector",
                    models.ForeignKey(
                        help_text="Detector that created this detection", on_delete=django.db.models.deletion.CASCADE, related_name="detections", to="alert_framework.detector"
                    ),
                ),
            ],
            options={
                "ordering": ["-detection_timestamp", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Template identifier", max_length=255, unique=True)),
                ("title", models.CharField(help_text="Alert title template", max_length=255)),
                ("text", models.TextField(help_text="Alert body template")),
                ("variables", models.JSONField(default=dict, help_text="Documentation of available template variables")),
                ("active", models.BooleanField(default=True, help_text="Template availability flag")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shock_type",
                    models.ForeignKey(help_text="Associated shock type", on_delete=django.db.models.deletion.CASCADE, related_name="alert_templates", to="alerts.shocktype"),
                ),
            ],
            options={
                "ordering": ["shock_type__name", "name"],
                "indexes": [
                    models.Index(fields=["shock_type", "active"], name="alert_frame_shock_t_e802e2_idx"),
                    models.Index(fields=["name"], name="alert_frame_name_942ea5_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="detector",
            index=models.Index(fields=["active", "name"], name="alert_frame_active_bfec12_idx"),
        ),
        migrations.AddIndex(
            model_name="detector",
            index=models.Index(fields=["last_run"], name="alert_frame_last_ru_f64e71_idx"),
        ),
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(fields=["detector", "status", "created_at"], name="alert_frame_detecto_227bcd_idx"),
        ),
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(fields=["detection_timestamp"], name="alert_frame_detecti_d3dfdb_idx"),
        ),
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(fields=["shock_type"], name="alert_frame_shock_t_652b38_idx"),
        ),
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(fields=["status", "created_at"], name="alert_frame_status_6ee8e5_idx"),
        ),
        migrations.AddConstraint(
            model_name="detection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("duplicate_of__isnull", True)), fields=("detector", "detection_timestamp"), name="unique_detector_timestamp_alert_framework"
            ),
        ),
    ]
