# Generated by Django 5.2.4 on 2025-09-12 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alert_framework", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishedAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("api_name", models.CharField(help_text="Name of the external API system", max_length=100)),
                ("external_id", models.CharField(blank=True, help_text="Alert ID in external system", max_length=255)),
                ("language", models.CharField(default="en", help_text="Language used for alert content", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("published", "Published"), ("failed", "Failed"), ("updated", "Updated"), ("cancelled", "Cancelled")],
                        default="pending",
                        help_text="Publication status",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, help_text="When alert was successfully published", null=True)),
                ("last_updated", models.DateTimeField(blank=True, help_text="When alert was last updated in external system", null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, help_text="When alert was cancelled", null=True)),
                ("cancellation_reason", models.TextField(blank=True, help_text="Reason for cancellation")),
                ("publication_metadata", models.JSONField(blank=True, default=dict, help_text="Response data from external API")),
                ("error_message", models.TextField(blank=True, help_text="Error details if publication failed")),
                ("retry_count", models.PositiveIntegerField(default=0, help_text="Number of publication retry attempts")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "detection",
                    models.ForeignKey(
                        help_text="Source detection for this alert", on_delete=django.db.models.deletion.CASCADE, related_name="published_alerts", to="alert_framework.detection"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="Template used for alert formatting",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_alerts",
                        to="alert_framework.alerttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["detection", "api_name"], name="alert_frame_detecti_dea4a3_idx"),
                    models.Index(fields=["status", "created_at"], name="alert_frame_status_4162ae_idx"),
                    models.Index(fields=["external_id"], name="alert_frame_externa_d3bba7_idx"),
                ],
                "unique_together": {("detection", "api_name", "language")},
            },
        ),
    ]
