# Generated by Django 5.2.4 on 2025-09-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alert_framework", "0002_publishedalert"),
        ("alerts", "0002_shocktype_color_shocktype_css_class_shocktype_icon"),
        ("location", "0010_unmatchedlocation_potential_matches_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="detection",
            name="unique_detector_timestamp_alert_framework",
        ),
        migrations.AddField(
            model_name="detection",
            name="title",
            field=models.CharField(default="", help_text="Detection title/name for identification", max_length=255),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="detection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("duplicate_of__isnull", True)), fields=("detector", "detection_timestamp", "title"), name="unique_detector_timestamp_title_alert_framework"
            ),
        ),
    ]
