# Generated by Django 5.2.4 on 2025-09-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alert_framework", "0003_remove_detection_unique_detector_timestamp_alert_framework_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alerttemplate",
            name="detector_type",
            field=models.CharField(blank=True, help_text="Optional filter for specific detector types", max_length=255),
        ),
    ]
