# Generated by Django 5.2.4 on 2025-10-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_framework', '0004_alerttemplate_detector_type'),
        ('alerts', '0004_add_performance_indexes'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('location', '0011_add_point_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alerttemplate',
            index=models.Index(fields=['active', 'shock_type'], name='alert_frame_active_85e637_idx'),
        ),
        migrations.AddIndex(
            model_name='alerttemplate',
            index=models.Index(fields=['detector_type'], name='alert_frame_detecto_1ee189_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['detector', 'detection_timestamp'], name='alert_frame_detecto_cdab00_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['status', 'detection_timestamp'], name='alert_frame_status_d14756_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['confidence_score'], name='alert_frame_confide_f8ba2b_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['duplicate_of'], name='alert_frame_duplica_8d1d08_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['processed_at'], name='alert_frame_process_fcb531_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['title'], name='alert_frame_title_af39df_idx'),
        ),
        migrations.AddIndex(
            model_name='detector',
            index=models.Index(fields=['active', 'last_run'], name='alert_frame_active_47d132_idx'),
        ),
        migrations.AddIndex(
            model_name='detector',
            index=models.Index(fields=['name'], name='alert_frame_name_985425_idx'),
        ),
        migrations.AddIndex(
            model_name='detector',
            index=models.Index(fields=['class_name'], name='alert_frame_class_n_6975fe_idx'),
        ),
        migrations.AddIndex(
            model_name='publishedalert',
            index=models.Index(fields=['status', 'published_at'], name='alert_frame_status_865ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='publishedalert',
            index=models.Index(fields=['api_name', 'status'], name='alert_frame_api_nam_3dee13_idx'),
        ),
        migrations.AddIndex(
            model_name='publishedalert',
            index=models.Index(fields=['retry_count'], name='alert_frame_retry_c_8eb172_idx'),
        ),
    ]
