# Generated by Django 5.2.4 on 2025-07-21 13:46

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdmLevel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(help_text="Administrative level code (e.g., '0' for country, '1' for admin1)", max_length=10, unique=True)),
                ("name", models.CharField(help_text="Name of the administrative level", max_length=100)),
                ("name_en", models.CharField(help_text="Name of the administrative level", max_length=100, null=True)),
                ("name_ar", models.CharField(help_text="Name of the administrative level", max_length=100, null=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "geo_id",
                    models.CharField(
                        help_text="Hierarchical geographic identifier (e.g., SD, SD_kha, SD_kha_001)",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="geo_id must follow format: XY for admin0, XY_abc for admin1, XY_abc_def for admin2, etc.", regex="^[A-Z]{2}(_[a-z0-9]{3})*$"
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(help_text="Name of the location", max_length=255)),
                ("name_en", models.CharField(help_text="Name of the location", max_length=255, null=True)),
                ("name_ar", models.CharField(help_text="Name of the location", max_length=255, null=True)),
                ("boundary", django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text="Geographic boundary", null=True, srid=4326)),
                ("point", django.contrib.gis.db.models.fields.PointField(blank=True, help_text="Representative point", null=True, srid=4326)),
                ("comment", models.TextField(blank=True, help_text="Additional information about the location")),
                ("comment_en", models.TextField(blank=True, help_text="Additional information about the location", null=True)),
                ("comment_ar", models.TextField(blank=True, help_text="Additional information about the location", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_level",
                    models.ForeignKey(
                        help_text="Administrative level of this location", on_delete=django.db.models.deletion.PROTECT, related_name="locations", to="location.admlevel"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent location in hierarchy",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="location.location",
                    ),
                ),
            ],
            options={
                "ordering": ["geo_id"],
            },
        ),
        migrations.CreateModel(
            name="Gazetteer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(help_text="Source of this name/code (e.g., 'ACLED', 'UNHCR', 'local')", max_length=100)),
                ("code", models.CharField(blank=True, help_text="Alternative code for the location", max_length=50)),
                ("name", models.CharField(help_text="Alternative name for the location", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Location this entry refers to", on_delete=django.db.models.deletion.CASCADE, related_name="gazetteer_entries", to="location.location"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["geo_id"], name="location_lo_geo_id_ebfb0f_idx"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["admin_level"], name="location_lo_admin_l_bd4483_idx"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["parent"], name="location_lo_parent__a571f7_idx"),
        ),
        migrations.AddIndex(
            model_name="gazetteer",
            index=models.Index(fields=["name"], name="location_ga_name_57efa3_idx"),
        ),
        migrations.AddIndex(
            model_name="gazetteer",
            index=models.Index(fields=["code"], name="location_ga_code_3ea8ed_idx"),
        ),
        migrations.AddIndex(
            model_name="gazetteer",
            index=models.Index(fields=["source"], name="location_ga_source_79ef4d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="gazetteer",
            unique_together={("location", "source", "code"), ("location", "source", "name")},
        ),
    ]
