# Generated by Django 5.2.4 on 2025-07-21 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='comment',
            field=models.TextField(blank=True, help_text='Additional information about the location', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='geo_id',
            field=models.CharField(help_text='Hierarchical geographic identifier (e.g., SD, SD_001, SD_001_002)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='geo_id must follow format: XY for admin0, XY_001 for admin1, XY_001_002 for admin2, etc.', regex='^[A-Z]{2}(_[0-9]{3,})*$')]),
        ),
    ]
