# Generated by Django 5.2.4 on 2025-09-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_location_created_at_alter_location_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gazetteer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='gazetteer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
