# Generated by Django 5.2.4 on 2025-09-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gazetteer',
            name='gazetteer_source_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='gazetteer',
            name='gazetteer_source_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='gazetteer',
            name='gazetteer_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='location_geo_id_level_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='location_geo_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='location_name_level_idx',
        ),
    ]
