# Generated by Django 5.2.4 on 2025-09-09 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_remove_gazetteer_gazetteer_source_code_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmatchedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Location name that failed to match', max_length=255)),
                ('code', models.CharField(blank=True, help_text='Location code if available', max_length=50)),
                ('admin_level', models.CharField(blank=True, help_text="Admin level if known (e.g., 'State', 'Locality')", max_length=50)),
                ('source', models.CharField(help_text="Source that provided this location (e.g., 'IDMC GIDD')", max_length=100)),
                ('context', models.TextField(blank=True, help_text='Additional context or full location string')),
                ('occurrence_count', models.IntegerField(default=1, help_text='Number of times this location failed to match')),
                ('first_seen', models.DateTimeField(auto_now_add=True, help_text='First time this location was seen')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Last time this location was seen')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('resolved', 'Resolved - Added to Gazetteer'), ('ignored', 'Ignored - Invalid/Test Data'), ('deferred', 'Deferred - Needs More Information')], default='pending', help_text='Review status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about resolution')),
                ('resolved_location', models.ForeignKey(blank=True, help_text='Location this was resolved to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_unmatched', to='location.location')),
            ],
            options={
                'ordering': ['-occurrence_count', '-last_seen'],
                'indexes': [models.Index(fields=['status'], name='location_un_status_5adfb6_idx'), models.Index(fields=['source'], name='location_un_source_ddf515_idx'), models.Index(fields=['-occurrence_count'], name='location_un_occurre_8f24c0_idx'), models.Index(fields=['-last_seen'], name='location_un_last_se_255913_idx')],
                'unique_together': {('name', 'source')},
            },
        ),
    ]
