# Generated by Django 5.2.4 on 2025-09-09 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_unmatchedlocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unmatchedlocation',
            name='is_matched',
            field=models.BooleanField(default=False, help_text='Whether this location has been matched to a location'),
        ),
        migrations.AddField(
            model_name='unmatchedlocation',
            name='matched_at',
            field=models.DateTimeField(blank=True, help_text='When this location was matched', null=True),
        ),
        migrations.AddField(
            model_name='unmatchedlocation',
            name='matched_by',
            field=models.ForeignKey(blank=True, help_text='User who performed the matching', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unmatchedlocation',
            name='original_location_text',
            field=models.TextField(blank=True, help_text='Original location text from source data (immutable)'),
        ),
    ]
