# Generated by Django 5.2.4 on 2025-09-09 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_add_matching_fields_to_unmatched_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unmatchedlocation',
            name='original_location_text',
        ),
    ]
