# Generated by Django 5.2.4 on 2025-09-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_add_original_location_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='unmatchedlocation',
            name='potential_matches',
            field=models.JSONField(blank=True, default=list, help_text='Precomputed list of potential location matches with similarity scores'),
        ),
        migrations.AddField(
            model_name='unmatchedlocation',
            name='potential_matches_computed_at',
            field=models.DateTimeField(blank=True, help_text='When the potential matches were last computed', null=True),
        ),
    ]
