# Generated by Django 5.2.4 on 2025-09-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_unmatchedlocation_potential_matches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='point_type',
            field=models.CharField(blank=True, choices=[('centroid', 'Centroid'), ('gps', 'GPS Coordinates')], help_text='Type of point geometry - centroid calculated from boundary or actual GPS coordinates', max_length=10, null=True),
        ),
    ]
