# Generated by Django 5.2.4 on 2025-09-18 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications_enabled', models.BooleanField(default=False, help_text='Master switch for email notifications - must be explicitly enabled')),
                ('email_verified', models.BooleanField(default=False, help_text="Whether the user's email has been verified")),
                ('email_verification_token', models.CharField(blank=True, help_text='Token for email verification', max_length=100)),
                ('email_verification_sent_at', models.DateTimeField(blank=True, help_text='When verification email was last sent', null=True)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('ar', 'العربية')], default='en', help_text="User's preferred language for communications", max_length=5)),
                ('timezone', models.CharField(choices=[('Africa/Khartoum', 'Sudan (Khartoum)'), ('UTC', 'UTC')], default='Africa/Khartoum', help_text="User's timezone for scheduling notifications", max_length=50)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='IP address of last login', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
