# Generated by Django 5.2.4 on 2025-07-21 13:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Name of the data source (e.g., ACLED, UNHCR)", max_length=255)),
                ("name_en", models.CharField(help_text="Name of the data source (e.g., ACLED, UNHCR)", max_length=255, null=True)),
                ("name_ar", models.CharField(help_text="Name of the data source (e.g., ACLED, UNHCR)", max_length=255, null=True)),
                ("description", models.TextField(blank=True, help_text="Description of the data source")),
                ("description_en", models.TextField(blank=True, help_text="Description of the data source", null=True)),
                ("description_ar", models.TextField(blank=True, help_text="Description of the data source", null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("api", "API"), ("web_scraping", "Web Scraping"), ("file_upload", "File Upload"), ("ftp", "FTP"), ("database", "Database")],
                        help_text="Type of data retrieval method",
                        max_length=20,
                    ),
                ),
                ("info_url", models.URLField(blank=True, help_text="URL with information about the data source")),
                ("base_url", models.URLField(blank=True, help_text="Base URL for API or website")),
                ("class_name", models.CharField(help_text="Python class name for data retrieval implementation", max_length=255)),
                ("comment", models.TextField(blank=True, help_text="Additional notes about the source")),
                ("comment_en", models.TextField(blank=True, help_text="Additional notes about the source", null=True)),
                ("comment_ar", models.TextField(blank=True, help_text="Additional notes about the source", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [models.Index(fields=["name"], name="data_pipeli_name_907609_idx"), models.Index(fields=["type"], name="data_pipeli_type_6fea6b_idx")],
            },
        ),
        migrations.CreateModel(
            name="TaskStatistics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(help_text="Date for these statistics", unique=True)),
                ("check_updates_count", models.IntegerField(default=0, help_text="Number of update check tasks")),
                ("download_data_count", models.IntegerField(default=0, help_text="Number of data download tasks")),
                ("process_data_count", models.IntegerField(default=0, help_text="Number of data processing tasks")),
                ("full_pipeline_count", models.IntegerField(default=0, help_text="Number of full pipeline tasks")),
                ("reprocess_data_count", models.IntegerField(default=0, help_text="Number of data reprocessing tasks")),
                ("success_count", models.IntegerField(default=0, help_text="Number of successful task executions")),
                ("failure_count", models.IntegerField(default=0, help_text="Number of failed task executions")),
                ("retry_count", models.IntegerField(default=0, help_text="Number of task retries")),
                ("avg_duration_seconds", models.FloatField(blank=True, help_text="Average task duration in seconds", null=True)),
                ("max_duration_seconds", models.FloatField(blank=True, help_text="Maximum task duration in seconds", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [models.Index(fields=["date"], name="data_pipeli_date_84ee66_idx")],
            },
        ),
        migrations.CreateModel(
            name="Variable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Human-readable name of the variable", max_length=255)),
                ("name_en", models.CharField(help_text="Human-readable name of the variable", max_length=255, null=True)),
                ("name_ar", models.CharField(help_text="Human-readable name of the variable", max_length=255, null=True)),
                ("code", models.CharField(help_text="Unique code for the variable (e.g., acled_fatalities)", max_length=100)),
                (
                    "period",
                    models.CharField(
                        choices=[("day", "Daily"), ("week", "Weekly"), ("month", "Monthly"), ("quarter", "Quarterly"), ("year", "Annual"), ("event", "Event-based")],
                        help_text="Temporal frequency of the data",
                        max_length=20,
                    ),
                ),
                ("adm_level", models.IntegerField(help_text="Administrative level (0=country, 1=admin1, etc.)", validators=[django.core.validators.MinValueValidator(0)])),
                (
                    "type",
                    models.CharField(
                        choices=[("quantitative", "Quantitative"), ("qualitative", "Qualitative"), ("textual", "Textual"), ("categorical", "Categorical")],
                        help_text="Type of data contained in this variable",
                        max_length=20,
                    ),
                ),
                ("text", models.TextField(blank=True, help_text="Additional description of the variable")),
                ("text_en", models.TextField(blank=True, help_text="Additional description of the variable", null=True)),
                ("text_ar", models.TextField(blank=True, help_text="Additional description of the variable", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        help_text="Data source this variable belongs to", on_delete=django.db.models.deletion.CASCADE, related_name="variables", to="data_pipeline.source"
                    ),
                ),
            ],
            options={
                "ordering": ["source__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="VariableData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField(help_text="Start date of the data period")),
                ("end_date", models.DateField(help_text="End date of the data period")),
                (
                    "period",
                    models.CharField(
                        choices=[("day", "Daily"), ("week", "Weekly"), ("month", "Monthly"), ("quarter", "Quarterly"), ("year", "Annual"), ("event", "Event-based")],
                        help_text="Period type of this data record",
                        max_length=20,
                    ),
                ),
                ("value", models.FloatField(blank=True, help_text="Numeric value (for quantitative data)", null=True)),
                ("text", models.TextField(blank=True, help_text="Text content (for qualitative/textual data)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("adm_level", models.ForeignKey(help_text="Administrative level of the location", on_delete=django.db.models.deletion.PROTECT, to="location.admlevel")),
                ("gid", models.ForeignKey(help_text="Geographic location identifier", on_delete=django.db.models.deletion.PROTECT, to="location.location")),
                (
                    "variable",
                    models.ForeignKey(
                        help_text="Variable this data belongs to", on_delete=django.db.models.deletion.CASCADE, related_name="data_records", to="data_pipeline.variable"
                    ),
                ),
            ],
            options={
                "ordering": ["-end_date", "gid__geo_id"],
            },
        ),
        migrations.AddIndex(
            model_name="variable",
            index=models.Index(fields=["source", "code"], name="data_pipeli_source__32461b_idx"),
        ),
        migrations.AddIndex(
            model_name="variable",
            index=models.Index(fields=["period", "adm_level"], name="data_pipeli_period_3475f2_idx"),
        ),
        migrations.AddIndex(
            model_name="variable",
            index=models.Index(fields=["type"], name="data_pipeli_type_df82e7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="variable",
            unique_together={("source", "code")},
        ),
        migrations.AddIndex(
            model_name="variabledata",
            index=models.Index(fields=["variable", "start_date", "end_date"], name="data_pipeli_variabl_a821b0_idx"),
        ),
        migrations.AddIndex(
            model_name="variabledata",
            index=models.Index(fields=["gid", "variable"], name="data_pipeli_gid_id_14af07_idx"),
        ),
        migrations.AddIndex(
            model_name="variabledata",
            index=models.Index(fields=["adm_level", "period"], name="data_pipeli_adm_lev_310bce_idx"),
        ),
        migrations.AddIndex(
            model_name="variabledata",
            index=models.Index(fields=["end_date"], name="data_pipeli_end_dat_d47fbd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="variabledata",
            unique_together={("variable", "start_date", "end_date", "gid")},
        ),
    ]
