# Generated by Django 5.2.4 on 2025-09-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the source is currently active'),
        ),
    ]
