# Generated by Django 5.2.4 on 2025-09-08 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0006_add_performance_indexes'),
        ('location', '0006_remove_gazetteer_gazetteer_source_code_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='variabledata',
            name='vardata_var_date_gid_idx',
        ),
        migrations.RemoveIndex(
            model_name='variabledata',
            name='vardata_var_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='variabledata',
            name='vardata_gid_date_idx',
        ),
        migrations.AddField(
            model_name='variabledata',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Reference to original data point for derived data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_records', to='data_pipeline.variabledata'),
        ),
        migrations.AddIndex(
            model_name='variabledata',
            index=models.Index(fields=['parent'], name='data_pipeli_parent__c36565_idx'),
        ),
    ]
