# Generated by Django 5.2.4 on 2025-09-09 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0007_remove_variabledata_vardata_var_date_gid_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variabledata',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Reference to original data point for derived data (e.g., aggregations, transformations)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_records', to='data_pipeline.variabledata'),
        ),
    ]
