# Generated by Django 5.2.4 on 2025-09-09 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0008_alter_variabledata_parent'),
        ('location', '0009_add_original_location_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='variabledata',
            name='original_location_text',
            field=models.TextField(blank=True, help_text='Original location text from source data (immutable)'),
        ),
        migrations.AlterField(
            model_name='variabledata',
            name='gid',
            field=models.ForeignKey(blank=True, help_text='Geographic location identifier (null if location not matched)', null=True, on_delete=django.db.models.deletion.PROTECT, to='location.location'),
        ),
    ]
