# Generated by Django 5.2.4 on 2025-09-09 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0009_add_original_location_text'),
        ('location', '0009_add_original_location_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='variabledata',
            name='unmatched_location',
            field=models.ForeignKey(blank=True, help_text='Reference to unmatched location record for reprocessing', null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.unmatchedlocation'),
        ),
    ]
