# Generated by Django 5.2.4 on 2025-09-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0010_add_unmatched_location_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='unit',
            field=models.CharField(blank=True, help_text="Unit of measurement (e.g., 'events', 'persons', 'USD')", max_length=50),
        ),
    ]
