# Generated by Django 5.2.4 on 2025-09-10 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0011_variable_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True, help_text='Access token for API authentication')),
                ('refresh_token', models.TextField(blank=True, help_text='Refresh token for renewing access token')),
                ('token_type', models.CharField(default='Bearer', help_text='Type of token (e.g., Bearer, Basic)', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('refresh_expires_at', models.DateTimeField(blank=True, help_text='When the refresh token expires', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional token-related metadata (scope, user info, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.OneToOneField(help_text='Data source this token belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='data_pipeline.source')),
            ],
            options={
                'ordering': ['source__name'],
                'indexes': [models.Index(fields=['source', 'expires_at'], name='data_pipeli_source__82391c_idx')],
            },
        ),
    ]
