# Generated by Django 5.2.4 on 2025-09-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0012_sourceauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='variabledata',
            name='raw_data',
            field=models.JSONField(blank=True, help_text='Original raw data from source (complete JSON record)', null=True),
        ),
    ]
