# Generated by Django 5.2.4 on 2025-08-29 14:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("data_pipeline", "0001_initial"),
        ("location", "0002_alter_location_comment_alter_location_geo_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShockType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Name of the shock type (e.g., Conflict, Natural disasters)", max_length=100, unique=True)),
                ("name_en", models.CharField(help_text="Name of the shock type (e.g., Conflict, Natural disasters)", max_length=100, null=True, unique=True)),
                ("name_ar", models.CharField(help_text="Name of the shock type (e.g., Conflict, Natural disasters)", max_length=100, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [models.Index(fields=["name"], name="alerts_shoc_name_467a5b_idx")],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Alert title/headline", max_length=255)),
                ("title_en", models.CharField(help_text="Alert title/headline", max_length=255, null=True)),
                ("title_ar", models.CharField(help_text="Alert title/headline", max_length=255, null=True)),
                ("text", models.TextField(help_text="Main alert content and details")),
                ("text_en", models.TextField(help_text="Main alert content and details", null=True)),
                ("text_ar", models.TextField(help_text="Main alert content and details", null=True)),
                ("shock_date", models.DateField(help_text="Date when the shock/event occurred")),
                ("go_no_go", models.BooleanField(default=False, help_text="Whether this alert has been approved for distribution (GO=True)")),
                ("go_no_go_date", models.DateTimeField(blank=True, help_text="When the go/no-go decision was made", null=True)),
                ("valid_from", models.DateTimeField(help_text="When this alert becomes valid/active")),
                ("valid_until", models.DateTimeField(help_text="When this alert expires")),
                (
                    "severity",
                    models.IntegerField(
                        choices=[(1, "Low"), (2, "Moderate"), (3, "High"), (4, "Very High"), (5, "Critical")],
                        help_text="Alert severity level (1=Low, 5=Critical)",
                        validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data_source", models.ForeignKey(help_text="Data source that triggered this alert", on_delete=django.db.models.deletion.PROTECT, to="data_pipeline.source")),
                ("locations", models.ManyToManyField(help_text="Geographic areas affected by this alert", to="location.location")),
                ("shock_type", models.ForeignKey(help_text="Category/type of this alert", on_delete=django.db.models.deletion.PROTECT, to="alerts.shocktype")),
            ],
            options={
                "ordering": ["-shock_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True, help_text="Whether this subscription is active")),
                ("method", models.CharField(choices=[("email", "Email")], default="email", help_text="Delivery method for alerts", max_length=20)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("immediate", "Immediate"), ("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")],
                        default="immediate",
                        help_text="How often to receive alert notifications",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("locations", models.ManyToManyField(help_text="Locations user wants to receive alerts for (filtered at adm1 level)", to="location.location")),
                ("shock_types", models.ManyToManyField(help_text="Types of alerts user wants to receive", to="alerts.shocktype")),
                ("user", models.ForeignKey(help_text="User who owns this subscription", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("received_at", models.DateTimeField(blank=True, help_text="When the user received this alert notification", null=True)),
                ("read_at", models.DateTimeField(blank=True, help_text="When the user first viewed/read this alert", null=True)),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        help_text="User's 1-5 star rating of alert accuracy",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
                    ),
                ),
                ("rating_at", models.DateTimeField(blank=True, help_text="When the user provided their rating", null=True)),
                ("flag_false", models.BooleanField(default=False, help_text="User flagged this alert as false")),
                ("flag_incomplete", models.BooleanField(default=False, help_text="User flagged this alert as incomplete")),
                ("comment", models.TextField(blank=True, help_text="User's structured feedback/comment on this alert")),
                ("bookmarked", models.BooleanField(default=False, help_text="User has bookmarked this alert")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("alert", models.ForeignKey(help_text="Alert that was interacted with", on_delete=django.db.models.deletion.CASCADE, to="alerts.alert")),
                ("user", models.ForeignKey(help_text="User who interacted with this alert", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(fields=["shock_type", "severity"], name="alerts_aler_shock_t_29cf6f_idx"),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(fields=["shock_date", "go_no_go"], name="alerts_aler_shock_d_6c3e4c_idx"),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(fields=["valid_from", "valid_until"], name="alerts_aler_valid_f_0473c3_idx"),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(fields=["go_no_go", "severity"], name="alerts_aler_go_no_g_dd4066_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["user", "active"], name="alerts_subs_user_id_a11961_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["active", "frequency"], name="alerts_subs_active_2911a4_idx"),
        ),
        migrations.AddIndex(
            model_name="useralert",
            index=models.Index(fields=["user", "bookmarked"], name="alerts_user_user_id_254826_idx"),
        ),
        migrations.AddIndex(
            model_name="useralert",
            index=models.Index(fields=["user", "read_at"], name="alerts_user_user_id_b2a95f_idx"),
        ),
        migrations.AddIndex(
            model_name="useralert",
            index=models.Index(fields=["alert", "rating"], name="alerts_user_alert_i_4a6ec7_idx"),
        ),
        migrations.AddIndex(
            model_name="useralert",
            index=models.Index(fields=["flag_false", "flag_incomplete"], name="alerts_user_flag_fa_e4e834_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="useralert",
            unique_together={("user", "alert")},
        ),
    ]
