# Generated by Django 5.2.4 on 2025-09-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shocktype',
            name='color',
            field=models.CharField(default='#6c757d', help_text='Hex color code for this shock type (e.g., #dc3545)', max_length=7),
        ),
        migrations.AddField(
            model_name='shocktype',
            name='css_class',
            field=models.CharField(blank=True, help_text='CSS class name for this shock type (auto-generated from name if empty)', max_length=50),
        ),
        migrations.AddField(
            model_name='shocktype',
            name='icon',
            field=models.CharField(default='📍', help_text='Icon/symbol to display for this shock type (emoji or symbol)', max_length=10),
        ),
    ]
