# Generated by Django 5.2.4 on 2025-09-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_shocktype_color_shocktype_css_class_shocktype_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('individual_alert', 'Individual Alert'), ('daily_digest', 'Daily Digest'), ('weekly_digest', 'Weekly Digest'), ('monthly_digest', 'Monthly Digest'), ('subscription_confirm', 'Subscription Confirmation'), ('email_verification', 'Email Verification')], help_text='Template identifier', max_length=50, unique=True)),
                ('description', models.TextField(help_text='Template purpose and usage')),
                ('subject', models.CharField(help_text='Email subject line with variables like {{alert.title}}', max_length=255)),
                ('subject_en', models.CharField(help_text='Email subject line with variables like {{alert.title}}', max_length=255, null=True)),
                ('subject_ar', models.CharField(help_text='Email subject line with variables like {{alert.title}}', max_length=255, null=True)),
                ('html_header', models.TextField(help_text='HTML content before main alert content')),
                ('html_header_en', models.TextField(help_text='HTML content before main alert content', null=True)),
                ('html_header_ar', models.TextField(help_text='HTML content before main alert content', null=True)),
                ('html_footer', models.TextField(help_text='HTML content after main alert content')),
                ('html_footer_en', models.TextField(help_text='HTML content after main alert content', null=True)),
                ('html_footer_ar', models.TextField(help_text='HTML content after main alert content', null=True)),
                ('html_wrapper', models.TextField(blank=True, help_text='Full HTML template with {{content}} placeholder')),
                ('html_wrapper_en', models.TextField(blank=True, help_text='Full HTML template with {{content}} placeholder', null=True)),
                ('html_wrapper_ar', models.TextField(blank=True, help_text='Full HTML template with {{content}} placeholder', null=True)),
                ('text_header', models.TextField(help_text='Text content before main alert content')),
                ('text_header_en', models.TextField(help_text='Text content before main alert content', null=True)),
                ('text_header_ar', models.TextField(help_text='Text content before main alert content', null=True)),
                ('text_footer', models.TextField(help_text='Text content after main alert content')),
                ('text_footer_en', models.TextField(help_text='Text content after main alert content', null=True)),
                ('text_footer_ar', models.TextField(help_text='Text content after main alert content', null=True)),
                ('text_wrapper', models.TextField(blank=True, help_text='Full text template with {{content}} placeholder')),
                ('text_wrapper_en', models.TextField(blank=True, help_text='Full text template with {{content}} placeholder', null=True)),
                ('text_wrapper_ar', models.TextField(blank=True, help_text='Full text template with {{content}} placeholder', null=True)),
                ('active', models.BooleanField(default=True, help_text='Whether this template is active and can be used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['name'],
            },
        ),
    ]
