# Generated by Django 5.2.4 on 2025-09-24 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_emailtemplate'),
        ('data_pipeline', '0013_variabledata_raw_data'),
        ('location', '0011_add_point_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['go_no_go', 'valid_from', 'valid_until'], name='alerts_aler_go_no_g_3f5c75_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['shock_type', 'go_no_go', 'severity'], name='alerts_aler_shock_t_cb55c6_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['created_at', 'go_no_go'], name='alerts_aler_created_e71838_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['go_no_go', 'shock_date', 'created_at'], name='alerts_aler_go_no_g_5302df_idx'),
        ),
        migrations.AddIndex(
            model_name='useralert',
            index=models.Index(fields=['user', 'alert', 'bookmarked'], name='alerts_user_user_id_0eb48b_idx'),
        ),
        migrations.AddIndex(
            model_name='useralert',
            index=models.Index(fields=['user', 'rating', 'rating_at'], name='alerts_user_user_id_d1ca06_idx'),
        ),
        migrations.AddIndex(
            model_name='useralert',
            index=models.Index(fields=['rating', 'created_at'], name='alerts_user_rating_f3c303_idx'),
        ),
    ]
