# Generated by Django 5.2.1 on 2025-06-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, help_text='Unique identifier for this translation string', max_length=100, unique=True)),
                ('value', models.TextField(help_text='The text content to be translated')),
                ('value_en', models.TextField(help_text='The text content to be translated', null=True)),
                ('value_fr', models.TextField(help_text='The text content to be translated', null=True)),
                ('value_es', models.TextField(help_text='The text content to be translated', null=True)),
                ('description', models.CharField(blank=True, help_text='Context description for translators', max_length=200)),
                ('description_en', models.CharField(blank=True, help_text='Context description for translators', max_length=200, null=True)),
                ('description_fr', models.CharField(blank=True, help_text='Context description for translators', max_length=200, null=True)),
                ('description_es', models.CharField(blank=True, help_text='Context description for translators', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this translation string is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this translation was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this translation was last updated')),
            ],
            options={
                'verbose_name': 'Translation String',
                'verbose_name_plural': 'Translation Strings',
                'ordering': ['label'],
            },
        ),
    ]
