# Generated by Django 5.2.4 on 2025-07-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translationstring',
            old_name='description_es',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='translationstring',
            old_name='value_es',
            new_name='value_ar',
        ),
        migrations.RemoveField(
            model_name='translationstring',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='translationstring',
            name='value_fr',
        ),
    ]
