# Generated by Django 5.2.4 on 2025-09-17 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(help_text='Unique provider identifier', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the provider is currently active')),
                ('priority', models.IntegerField(default=100, help_text='Provider selection priority (lower = higher priority)')),
                ('config', models.JSONField(default=dict, help_text='Provider-specific configuration')),
                ('rate_limit', models.IntegerField(blank=True, help_text='Requests per minute limit', null=True)),
                ('token_limit', models.IntegerField(blank=True, help_text='Tokens per day limit', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider Configuration',
                'verbose_name_plural': 'Provider Configurations',
                'ordering': ['priority', 'provider_name'],
            },
        ),
        migrations.CreateModel(
            name='CachedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text='Unique cache identifier (SHA-256 hash)', max_length=64, unique=True)),
                ('provider', models.CharField(help_text='Provider that generated response', max_length=50)),
                ('model', models.CharField(help_text='Model used', max_length=100)),
                ('response_text', models.TextField(help_text='Cached response content')),
                ('response_metadata', models.JSONField(default=dict, help_text='Response metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Cache expiration time')),
                ('hit_count', models.IntegerField(default=0, help_text='Number of cache hits')),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last cache hit timestamp')),
            ],
            options={
                'verbose_name': 'Cached Response',
                'verbose_name_plural': 'Cached Responses',
                'ordering': ['-last_accessed'],
                'indexes': [models.Index(fields=['provider', 'model', 'created_at'], name='llm_service_provide_dc8e46_idx')],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, help_text='Provider identifier', max_length=50)),
                ('model', models.CharField(help_text='Model name used', max_length=100)),
                ('prompt_hash', models.CharField(db_index=True, help_text='SHA-256 hash of prompt for privacy', max_length=64)),
                ('tokens_input', models.IntegerField(default=0, help_text='Input token count')),
                ('tokens_output', models.IntegerField(default=0, help_text='Output token count')),
                ('total_tokens', models.IntegerField(default=0, help_text='Total tokens used')),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('success', models.BooleanField(default=True, help_text='Query success status')),
                ('error_message', models.TextField(blank=True, help_text='Error details if failed', null=True)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=6, help_text='Estimated cost in USD', max_digits=10, null=True)),
                ('application', models.CharField(db_index=True, help_text='Calling application identifier', max_length=100)),
                ('metadata', models.JSONField(default=dict, help_text='Additional query metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who made the query', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Query Log',
                'verbose_name_plural': 'Query Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'created_at'], name='llm_service_provide_084a13_idx'), models.Index(fields=['application', 'created_at'], name='llm_service_applica_095561_idx')],
            },
        ),
    ]
