# Generated by Django 5.2.4 on 2025-09-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='prompt_text',
            field=models.TextField(blank=True, help_text='Original prompt text (if logging enabled)', null=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='response_text',
            field=models.TextField(blank=True, help_text='LLM response text (if logging enabled)', null=True),
        ),
    ]
