# Generated by Django 5.2.4 on 2025-09-18 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0003_emailtemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_enabled', models.BooleanField(default=True, help_text='Receive in-app notifications')),
                ('alert_notifications', models.BooleanField(default=True, help_text='Receive notifications for new alerts')),
                ('system_notifications', models.BooleanField(default=True, help_text='Receive system notifications')),
                ('update_notifications', models.BooleanField(default=True, help_text='Receive alert update notifications')),
                ('feedback_notifications', models.BooleanField(default=True, help_text='Receive feedback response notifications')),
                ('show_desktop_notifications', models.BooleanField(default=False, help_text='Show browser desktop notifications')),
                ('play_sound', models.BooleanField(default=False, help_text='Play sound for urgent notifications')),
                ('quiet_hours_enabled', models.BooleanField(default=False, help_text='Enable quiet hours for non-urgent notifications')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start time for quiet hours', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End time for quiet hours', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='InternalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('alert', 'New Alert'), ('system', 'System Message'), ('update', 'Alert Update'), ('feedback', 'Feedback Response'), ('subscription', 'Subscription Update')], default='alert', help_text='Type of notification', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Priority level of the notification', max_length=10)),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('message', models.TextField(help_text='Notification message content')),
                ('read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL for action button if applicable', max_length=500)),
                ('action_text', models.CharField(blank=True, help_text='Text for action button if applicable', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this notification expires and can be auto-deleted', null=True)),
                ('alert', models.ForeignKey(blank=True, help_text='Related alert if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, to='alerts.alert')),
                ('user', models.ForeignKey(help_text='User who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Internal Notification',
                'verbose_name_plural': 'Internal Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read'], name='notificatio_user_id_fe4948_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_7307ab_idx'), models.Index(fields=['type', 'priority'], name='notificatio_type_288904_idx')],
            },
        ),
    ]
